/* Never Roam Alone — featured-city photos (all 123 guide cities).
   Local files under images/cities/, downloaded from Wikimedia Commons
   (each city's Wikipedia lead image, or an iconic-landmark article where
   the city article leads with a flag/map). page = file page for credit.
   Pages fall back to placeholders for any city missing here. */
window.NRA_CITY_PHOTO = {
  "Abu Dhabi": { img:"images/cities/abu-dhabi.jpg", page:"https://commons.wikimedia.org/wiki/File:Abu_dhabi_skylines_2014.jpg" },
  "Amsterdam": { img:"images/cities/amsterdam.jpg", page:"https://commons.wikimedia.org/wiki/File:Imagen_de_los_canales_conc%C3%A9ntricos_en_%C3%81msterdam.png" },
  "Andorra la Vella": { img:"images/cities/andorra-la-vella.jpg", page:"https://en.wikipedia.org/wiki/File:Casa_de_la_Vall_4.JPG" },
  "Antalya": { img:"images/cities/antalya.jpg", page:"https://commons.wikimedia.org/wiki/File:Falezlerden_Antalya_Konyaalt%C4%B1_Plaj%C4%B1na_do%C4%9Fru_bir_g%C3%B6r%C3%BCn%C3%BCm.jpg" },
  "Athens": { img:"images/cities/athens.jpg", page:"https://commons.wikimedia.org/wiki/File:Monastiraki_Square_and_Acropolis_in_Athens_(44149181684).jpg" },
  "Bangkok": { img:"images/cities/bangkok.jpg", page:"https://commons.wikimedia.org/wiki/File:4Y1A1159_Bangkok_(33536795515).jpg" },
  "Barcelona": { img:"images/cities/barcelona.jpg", page:"https://commons.wikimedia.org/wiki/File:Evening_light_over_Barcelona.jpg" },
  "Beijing": { img:"images/cities/beijing.jpg", page:"https://commons.wikimedia.org/wiki/File:Skyline_of_Beijing_CBD_with_B-5906_approaching_(20211016171955)_(1).jpg" },
  "Belgrade": { img:"images/cities/belgrade.jpg", page:"https://commons.wikimedia.org/wiki/File:Panorama_Belgrad.jpg" },
  "Berlin": { img:"images/cities/berlin.jpg", page:"https://commons.wikimedia.org/wiki/File:Museumsinsel_Berlin_Juli_2021_1_(cropped)_b.jpg" },
  "Bologna": { img:"images/cities/bologna.jpg", page:"https://commons.wikimedia.org/wiki/File:Torri_di_Bologna%2C_Bologna.jpg" },
  "Bratislava": { img:"images/cities/bratislava.jpg", page:"https://commons.wikimedia.org/wiki/File:Slovakia_bratislava.jpg" },
  "Brussels": { img:"images/cities/brussels.jpg", page:"https://commons.wikimedia.org/wiki/File:Grand_Place_Bruselas_2.jpg" },
  "Bucharest": { img:"images/cities/bucharest.jpg", page:"https://commons.wikimedia.org/wiki/File:Bucharest_University_Square_(cropped).jpg" },
  "Budapest": { img:"images/cities/budapest.jpg", page:"https://commons.wikimedia.org/wiki/File:View_from_Gell%C3%A9rt_Hill_to_the_Danube%2C_Hungary_-_Budapest_(28493220635).jpg" },
  "Buenos Aires": { img:"images/cities/buenos-aires.jpg", page:"https://commons.wikimedia.org/wiki/File:Avenida_9_de_Julio%2C_Buenos_Aires_(40089810910).jpg" },
  "Busan": { img:"images/cities/busan.jpg", page:"https://commons.wikimedia.org/wiki/File:Gwangan_Bridge1.jpg" },
  "Cairo": { img:"images/cities/cairo.jpg", page:"https://commons.wikimedia.org/wiki/File:Cairo_Opera_House%2C_Al_Hurriyah_Park_and_the_Nile_river_(14797782354).jpg" },
  "Cancún": { img:"images/cities/canc-n.jpg", page:"https://commons.wikimedia.org/wiki/File:Cancun_Strand_Luftbild_(22143397586).jpg" },
  "Cape Town": { img:"images/cities/cape-town.jpg", page:"https://commons.wikimedia.org/wiki/File:Camps_bay_(53460319478)_(cropped).jpg" },
  "Chișinău": { img:"images/cities/chi-in-u.jpg", page:"https://commons.wikimedia.org/wiki/File:Consiliul_Municipal_Chi%C8%99in%C4%83u_(cropped).jpg" },
  "Copenhagen": { img:"images/cities/copenhagen.jpg", page:"https://commons.wikimedia.org/wiki/File:2018_-_Christiansborg_from_the_Marble_Bridge.jpg" },
  "Delhi": { img:"images/cities/delhi.jpg", page:"https://commons.wikimedia.org/wiki/File:Jama_Masjid_2011.jpg" },
  "Denpasar": { img:"images/cities/denpasar.jpg", page:"https://commons.wikimedia.org/wiki/File:Aerial_view_of_Bajra_Sandhi_Monument_Denpasar_Bali_Indonesia.jpg" },
  "Doha": { img:"images/cities/doha.jpg", page:"https://commons.wikimedia.org/wiki/File:The_Pearl_Marina_in_Nov_2013.jpg" },
  "Dubai": { img:"images/cities/dubai.jpg", page:"https://en.wikipedia.org/wiki/File:Burj_Khalifa_2021.jpg" },
  "Dublin": { img:"images/cities/dublin.jpg", page:"https://commons.wikimedia.org/wiki/File:Dublin_-_aerial_-_2025-07-07_01.jpg" },
  "Dubrovnik": { img:"images/cities/dubrovnik.jpg", page:"https://commons.wikimedia.org/wiki/File:The_walls_of_the_fortress_and_View_of_the_old_city._panorama.jpg" },
  "Edinburgh": { img:"images/cities/edinburgh.jpg", page:"https://commons.wikimedia.org/wiki/File:Skyline_of_Edinburgh.jpg" },
  "Florence": { img:"images/cities/florence.jpg", page:"https://commons.wikimedia.org/wiki/File:FirenzeDec092023_01.jpg" },
  "Frankfurt am Main": { img:"images/cities/frankfurt-am-main.jpg", page:"https://en.wikipedia.org/wiki/File:Frankfurt_Main_August_2020_1.jpg" },
  "Fukuoka": { img:"images/cities/fukuoka.jpg", page:"https://commons.wikimedia.org/wiki/File:Fukuoka_Skyline_of_Seaside_Momochi.jpg" },
  "Guangzhou": { img:"images/cities/guangzhou.jpg", page:"https://commons.wikimedia.org/wiki/File:Canton_Tower_20241027.jpg" },
  "Hanoi": { img:"images/cities/hanoi.jpg", page:"https://commons.wikimedia.org/wiki/File:Hanoi_skyline_with_Ba_Vi_Mountain.jpg" },
  "Helsinki": { img:"images/cities/helsinki.jpg", page:"https://commons.wikimedia.org/wiki/File:Suomenlinna_(cropped).jpg" },
  "Heraklion": { img:"images/cities/heraklion.jpg", page:"https://commons.wikimedia.org/wiki/File:Heraklion_Montage_L.png" },
  "Ho Chi Minh City": { img:"images/cities/ho-chi-minh-city.jpg", page:"https://commons.wikimedia.org/wiki/File:Ho_Chi_Minh_City_panorama_2019_(cropped2).jpg" },
  "Hong Kong": { img:"images/cities/hong-kong.jpg", page:"https://commons.wikimedia.org/wiki/File:Hong_Kong_Skyline_viewed_from_Victoria_Peak.jpg" },
  "Honolulu": { img:"images/cities/honolulu.jpg", page:"https://commons.wikimedia.org/wiki/File:2022_Views_from_Diamond_Head_02.jpg" },
  "Istanbul": { img:"images/cities/istanbul.jpg", page:"https://commons.wikimedia.org/wiki/File:Historical_peninsula_and_modern_skyline_of_Istanbul.jpg" },
  "Jerusalem": { img:"images/cities/jerusalem.jpg", page:"https://commons.wikimedia.org/wiki/File:Dome_of_the_Rock_seen_from_the_Mount_of_Olives_(12395649153)_(cropped).jpg" },
  "Johor Bahru": { img:"images/cities/johor-bahru.jpg", page:"https://commons.wikimedia.org/wiki/File:Johor_Bahru_at_night.png" },
  "Kotor": { img:"images/cities/kotor.jpg", page:"https://commons.wikimedia.org/wiki/File:20090719_Crkva_Gospa_od_Zdravlja_Kotor_Bay_Montenegro.jpg" },
  "Kraków": { img:"images/cities/krak-w.jpg", page:"https://commons.wikimedia.org/wiki/File:Krakow_Rynek_Glowny_panorama_2.jpg" },
  "Kuala Lumpur": { img:"images/cities/kuala-lumpur.jpg", page:"https://commons.wikimedia.org/wiki/File:Bukit_Bintang_junction_in_2024_2.jpg" },
  "Kyiv": { img:"images/cities/kyiv.jpg", page:"https://commons.wikimedia.org/wiki/File:%D0%91%D1%83%D0%B4%D0%B8%D0%BD%D0%BE%D0%BA_%D0%B7_%D1%85%D0%B8%D0%BC%D0%B5%D1%80%D0%B0%D0%BC%D0%B8%2C_%D1%81%D0%B5%D1%80%D0%BF%D0%B5%D0%BD%D1%8C_2019.jpg" },
  "Kyoto": { img:"images/cities/kyoto.jpg", page:"https://commons.wikimedia.org/wiki/File:Kiyomizu.jpg" },
  "Las Vegas": { img:"images/cities/las-vegas.jpg", page:"https://commons.wikimedia.org/wiki/File:Las_Vegas_from_above_(40064746644).jpg" },
  "Lima": { img:"images/cities/lima.jpg", page:"https://commons.wikimedia.org/wiki/File:Bas%C3%ADlica_Catedral_Metropolitana_de_Lima_(cropped).jpg" },
  "Lisbon": { img:"images/cities/lisbon.jpg", page:"https://commons.wikimedia.org/wiki/File:Lisboa_-_Portugal_(52597836992).jpg" },
  "Ljubljana": { img:"images/cities/ljubljana.jpg", page:"https://commons.wikimedia.org/wiki/File:Ljubljana_Old_Town%2C_Slovenia_(Old_Camera)_(33286165680).jpg" },
  "London": { img:"images/cities/london.jpg", page:"https://commons.wikimedia.org/wiki/File:London_Skyline_(125508655).jpeg" },
  "Los Angeles": { img:"images/cities/los-angeles.jpg", page:"https://commons.wikimedia.org/wiki/File:Hollywood_Sign_(Zuschnitt).jpg" },
  "Luxembourg City": { img:"images/cities/luxembourg-city.jpg", page:"https://commons.wikimedia.org/wiki/File:Luxembourg_Grand_Ducal_Palace_01.jpg" },
  "Macau": { img:"images/cities/macau.jpg", page:"https://commons.wikimedia.org/wiki/File:%E5%A4%A7%E4%B8%89%E5%B7%B4%E7%89%8C%E5%9D%8A.jpg" },
  "Madrid": { img:"images/cities/madrid.jpg", page:"https://commons.wikimedia.org/wiki/File:Plaza_Mayor_De_Madrid_(215862629)_edited.jpeg" },
  "Marne-la-Vallée": { img:"images/cities/marne-la-vall-e.jpg", page:"https://en.wikipedia.org/wiki/File:Sleeping_Beauty_Castle%2C_Disneyland%2C_Paris.jpg" },
  "Marrakech": { img:"images/cities/marrakech.jpg", page:"https://commons.wikimedia.org/wiki/File:Pavillon_Menarag%C3%A4rten.jpg" },
  "Mecca": { img:"images/cities/mecca.jpg", page:"https://commons.wikimedia.org/wiki/File:Great_Mosque_of_Mecca1.jpg" },
  "Medina": { img:"images/cities/medina.jpg", page:"https://commons.wikimedia.org/wiki/File:Al-Masjid_An-Nabawi_(Bird's_Eye_View).jpg" },
  "Melbourne": { img:"images/cities/melbourne.jpg", page:"https://commons.wikimedia.org/wiki/File:Melbourne_skyline_sor.jpg" },
  "Mexico City": { img:"images/cities/mexico-city.jpg", page:"https://commons.wikimedia.org/wiki/File:Sobrevuelos_CDMX_HJ2A4913_(25514321687)_(cropped).jpg" },
  "Miami": { img:"images/cities/miami.jpg", page:"https://commons.wikimedia.org/wiki/File:Villa_Vizcaya_20110228.jpg" },
  "Milan": { img:"images/cities/milan.jpg", page:"https://commons.wikimedia.org/wiki/File:Milan_-_Scala_-_Facade.jpg" },
  "Minsk": { img:"images/cities/minsk.jpg", page:"https://commons.wikimedia.org/wiki/File:View_of_Minsk_(180819)_09.jpg" },
  "Monaco": { img:"images/cities/monaco.jpg", page:"https://commons.wikimedia.org/wiki/File:Panorama_von_Monaco-La_Turbie.jpg" },
  "Montreal": { img:"images/cities/montreal.jpg", page:"https://commons.wikimedia.org/wiki/File:Montreal%2C_Quebec_skyline.jpg" },
  "Moscow": { img:"images/cities/moscow.jpg", page:"https://commons.wikimedia.org/wiki/File:Saint_Basil's_Cathedral_and_the_Red_Square.jpg" },
  "Munich": { img:"images/cities/munich.jpg", page:"https://commons.wikimedia.org/wiki/File:Stadtbild_M%C3%BCnchen.jpg" },
  "New York": { img:"images/cities/new-york.jpg", page:"https://commons.wikimedia.org/wiki/File:View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_(cropped).jpg" },
  "Nice": { img:"images/cities/nice.jpg", page:"https://commons.wikimedia.org/wiki/File:Promenade_des_Anglais_Nice_IMG_1255.jpg" },
  "Orlando": { img:"images/cities/orlando.jpg", page:"https://commons.wikimedia.org/wiki/File:Orlando%2C_Florida_(cropped).jpg" },
  "Osaka": { img:"images/cities/osaka.jpg", page:"https://commons.wikimedia.org/wiki/File:Osaka_Castle_02bs3200.jpg" },
  "Oslo": { img:"images/cities/oslo.jpg", page:"https://commons.wikimedia.org/wiki/File:Nationaltheatret_evening.jpg" },
  "Palma de Mallorca": { img:"images/cities/palma-de-mallorca.jpg", page:"https://commons.wikimedia.org/wiki/File:Kathedrale_von_Palma.jpg" },
  "Paris": { img:"images/cities/paris.jpg", page:"https://commons.wikimedia.org/wiki/File:La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_(2).jpg" },
  "Pattaya-Chonburi": { img:"images/cities/pattaya-chonburi.jpg", page:"https://commons.wikimedia.org/wiki/File:Pattaya_beach_from_view_point.jpg" },
  "Phuket": { img:"images/cities/phuket.jpg", page:"https://commons.wikimedia.org/wiki/File:Phuket_Aerial.jpg" },
  "Porto": { img:"images/cities/porto.jpg", page:"https://commons.wikimedia.org/wiki/File:Puente_Don_Luis_I%2C_Oporto%2C_Portugal%2C_2012-05-09%2C_DD_13.JPG" },
  "Prague": { img:"images/cities/prague.jpg", page:"https://commons.wikimedia.org/wiki/File:Prague_(6365119737).jpg" },
  "Punta Cana": { img:"images/cities/punta-cana.jpg", page:"https://commons.wikimedia.org/wiki/File:Cap_Cana_Marina_Dominican_Republic.jpg" },
  "Reykjavík": { img:"images/cities/reykjav-k.jpg", page:"https://commons.wikimedia.org/wiki/File:Reykjav%C3%ADk%2C_view_from_Hallgr%C3%ADmskirkja_(2).jpg" },
  "Rhodes": { img:"images/cities/rhodes.jpg", page:"https://commons.wikimedia.org/wiki/File:Medieval_City_of_Rhodes_03.jpg" },
  "Riga": { img:"images/cities/riga.jpg", page:"https://commons.wikimedia.org/wiki/File:Riga_(33844464828).jpg" },
  "Rio de Janeiro": { img:"images/cities/rio-de-janeiro.jpg", page:"https://commons.wikimedia.org/wiki/File:Cidade_Maravilhosa.jpg" },
  "Riyadh": { img:"images/cities/riyadh.jpg", page:"https://commons.wikimedia.org/wiki/File:Riyadh_Skyline.jpg" },
  "Rome": { img:"images/cities/rome.jpg", page:"https://commons.wikimedia.org/wiki/File:Trevi_Fountain%2C_Rome%2C_Italy_2_-_May_2007.jpg" },
  "San Francisco": { img:"images/cities/san-francisco.jpg", page:"https://commons.wikimedia.org/wiki/File:San_Francisco_Downtown_Aerial%2C_August_2025.jpg" },
  "San Marino": { img:"images/cities/san-marino.jpg", page:"https://commons.wikimedia.org/wiki/File:Basilica_del_Santo_Marino%2C_San_Marino%2C_2022-09-20%2C_DD_11.jpg" },
  "Santiago": { img:"images/cities/santiago.jpg", page:"https://commons.wikimedia.org/wiki/File:Palacio_de_La_Moneda_-_miguelreflex.jpg" },
  "São Paulo": { img:"images/cities/s-o-paulo.jpg", page:"https://commons.wikimedia.org/wiki/File:Marginal_Pinheiros_e_Jockey_Club.jpg" },
  "Sapporo": { img:"images/cities/sapporo.jpg", page:"https://commons.wikimedia.org/wiki/File:SapporoCity_Skylines2020.jpg" },
  "Sarajevo": { img:"images/cities/sarajevo.jpg", page:"https://commons.wikimedia.org/wiki/File:Sarajevo_City_Panorama.JPG" },
  "Seoul": { img:"images/cities/seoul.jpg", page:"https://en.wikipedia.org/wiki/File:%EC%A4%91%ED%99%94%EC%A0%84%EC%9D%98_%EB%82%AE.jpg" },
  "Seville": { img:"images/cities/seville.jpg", page:"https://commons.wikimedia.org/wiki/File:Sevilla_Cathedral_-_Southeast.jpg" },
  "Shanghai": { img:"images/cities/shanghai.jpg", page:"https://commons.wikimedia.org/wiki/File:Huangpu_Park_20124-Shanghai_(32208802494).jpg" },
  "Sharjah": { img:"images/cities/sharjah.jpg", page:"https://commons.wikimedia.org/wiki/File:Al_Qasba.jpg" },
  "Shenzhen": { img:"images/cities/shenzhen.jpg", page:"https://commons.wikimedia.org/wiki/File:Commercial_area_of_futian_to_east2020.jpg" },
  "Singapore": { img:"images/cities/singapore.jpg", page:"https://commons.wikimedia.org/wiki/File:Singapore_Skyline_2019-10.jpg" },
  "Skopje": { img:"images/cities/skopje.jpg", page:"https://commons.wikimedia.org/wiki/File:Skopje_view_from_Kale_3.jpg" },
  "Sofia": { img:"images/cities/sofia.jpg", page:"https://commons.wikimedia.org/wiki/File:Russian_church_(37591925970).jpg" },
  "Stockholm": { img:"images/cities/stockholm.jpg", page:"https://commons.wikimedia.org/wiki/File:Royal_Dramatic_Theatre_Stockholm.jpg" },
  "Sydney": { img:"images/cities/sydney.jpg", page:"https://commons.wikimedia.org/wiki/File:Sydney_Opera_House_and_Harbour_Bridge_Dusk_(2)_2019-06-21.jpg" },
  "Taipei": { img:"images/cities/taipei.jpg", page:"https://commons.wikimedia.org/wiki/File:Taipei_Skyline_2022.06.29.jpg" },
  "Tallinn": { img:"images/cities/tallinn.jpg", page:"https://commons.wikimedia.org/wiki/File:Raekoja_plats_at_night.jpg" },
  "Tbilisi": { img:"images/cities/tbilisi.jpg", page:"https://commons.wikimedia.org/wiki/File:View_of_Tbilisi_from_Tabori_Church_2023-10-08-2.jpg" },
  "Tel Aviv": { img:"images/cities/tel-aviv.jpg", page:"https://commons.wikimedia.org/wiki/File:Sarona_CBD_01_(cropped).jpg" },
  "Thessaloniki": { img:"images/cities/thessaloniki.jpg", page:"https://commons.wikimedia.org/wiki/File:Thessaloniki_Heptapyrgion_northeastern_wall_from_the_inner_yard.jpg" },
  "Tirana": { img:"images/cities/tirana.jpg", page:"https://commons.wikimedia.org/wiki/File:Skanderbeg_square_tirana_2016.jpg" },
  "Tokyo": { img:"images/cities/tokyo.jpg", page:"https://en.wikipedia.org/wiki/File:Skyscrapers_of_Shinjuku_2009_January.jpg" },
  "Toronto": { img:"images/cities/toronto.jpg", page:"https://commons.wikimedia.org/wiki/File:Toronto_Skyline_from_Olympic_Island%2C_June_20_2026_(5-3_cropped).jpg" },
  "Vaduz": { img:"images/cities/vaduz.jpg", page:"https://commons.wikimedia.org/wiki/File:View_of_Vaduz.jpg" },
  "Valencia": { img:"images/cities/valencia.jpg", page:"https://commons.wikimedia.org/wiki/File:Malvarrosa_Beach%2C_Valencia%2C_Spain_(29812271043).jpg" },
  "Valletta": { img:"images/cities/valletta.jpg", page:"https://commons.wikimedia.org/wiki/File:St_Sebastian_Curtain_(cropped).jpg" },
  "Vancouver": { img:"images/cities/vancouver.jpg", page:"https://commons.wikimedia.org/wiki/File:Skyline_of_Vancouver%2C_Canada.jpg" },
  "Venice": { img:"images/cities/venice.jpg", page:"https://commons.wikimedia.org/wiki/File:Venezia_aerial_view.jpg" },
  "Verona": { img:"images/cities/verona.jpg", page:"https://commons.wikimedia.org/wiki/File:Tramonto_a_Verona.jpg" },
  "Vienna": { img:"images/cities/vienna.jpg", page:"https://commons.wikimedia.org/wiki/File:Schoenbrunn_philharmoniker_2012.jpg" },
  "Vilnius": { img:"images/cities/vilnius.jpg", page:"https://en.wikipedia.org/wiki/File:The_White_Bridge_and_%C5%A0nipi%C5%A1k%C4%97s_district_in_Vilnius_in_2023_by_Augustas_Did%C5%BEgalvis.jpg" },
  "Warsaw": { img:"images/cities/warsaw.jpg", page:"https://commons.wikimedia.org/wiki/File:Aleja_Niepdleglosci_Warsaw_2022_aerial_(cropped).jpg" },
  "Washington, D.C.": { img:"images/cities/washington-d-c.jpg", page:"https://commons.wikimedia.org/wiki/File:12-07-13-washington-by-RalfR-08.jpg" },
  "Zhuhai": { img:"images/cities/zhuhai.jpg", page:"https://commons.wikimedia.org/wiki/File:%E4%BB%8E%E5%87%A4%E5%87%B0%E5%B1%B1%E8%BF%9C%E7%9C%BA%E7%8F%A0%E6%B5%B7%E4%B8%BB%E5%9F%8E%E5%8C%BA.jpg" },
  "Zurich": { img:"images/cities/zurich.jpg", page:"https://commons.wikimedia.org/wiki/File:Altstadt_Z%C3%BCrich_2015.jpg" }
};
