/* Never Roam Alone — featured-city photos (all 123 guide cities).
   Local files under images/cities/, downloaded from Wikimedia Commons
   (each city's Wikipedia lead image, or an iconic-landmark article where
   the city article leads with a flag/map). page = file page for credit.
   Pages fall back to placeholders for any city missing here. */
window.NRA_CITY_PHOTO = {
  "Abu Dhabi": { img:"images/cities/abu-dhabi.jpg", page:"https://commons.wikimedia.org/wiki/File:Abu_dhabi_skylines_2014.jpg" },
  "Amsterdam": { img:"images/cities/amsterdam.jpg", page:"https://commons.wikimedia.org/wiki/File:Imagen_de_los_canales_conc%C3%A9ntricos_en_%C3%81msterdam.png" },
  "Andorra la Vella": { img:"images/cities/andorra-la-vella.jpg", page:"https://commons.wikimedia.org/wiki/File:Vista_de_Andorra_la_Vieja,_Andorra,_2013-12-30,_DD_01.JPG" },
  "Antalya": { img:"images/cities/antalya.jpg", page:"https://commons.wikimedia.org/wiki/File:Falezlerden_Antalya_Konyaalt%C4%B1_Plaj%C4%B1na_do%C4%9Fru_bir_g%C3%B6r%C3%BCn%C3%BCm.jpg" },
  "Athens": { img:"images/cities/athens.jpg", page:"https://commons.wikimedia.org/wiki/File:Monastiraki_Square_and_Acropolis_in_Athens_(44149181684).jpg" },
  "Bangkok": { img:"images/cities/bangkok.jpg", page:"https://commons.wikimedia.org/wiki/File:4Y1A1159_Bangkok_(33536795515).jpg" },
  "Barcelona": { img:"images/cities/barcelona.jpg", page:"https://commons.wikimedia.org/wiki/File:Evening_light_over_Barcelona.jpg" },
  "Beijing": { img:"images/cities/beijing.jpg", page:"https://commons.wikimedia.org/wiki/File:Skyline_of_Beijing_CBD_with_B-5906_approaching_(20211016171955)_(1).jpg" },
  "Belgrade": { img:"images/cities/belgrade.jpg", page:"https://commons.wikimedia.org/wiki/File:Panorama_Belgrad.jpg" },
  "Berlin": { img:"images/cities/berlin.jpg", page:"https://commons.wikimedia.org/wiki/File:Museumsinsel_Berlin_Juli_2021_1_(cropped)_b.jpg" },
  "Bologna": { img:"images/cities/bologna.jpg", page:"https://commons.wikimedia.org/wiki/File:Torri_di_Bologna%2C_Bologna.jpg" },
  "Bratislava": { img:"images/cities/bratislava.jpg", page:"https://commons.wikimedia.org/wiki/File:Slovakia_bratislava.jpg" },
  "Brussels": { img:"images/cities/brussels.jpg", page:"https://commons.wikimedia.org/wiki/File:Grand_Place_Bruselas_2.jpg" },
  "Bucharest": { img:"images/cities/bucharest.jpg", page:"https://commons.wikimedia.org/wiki/File:Bucharest_University_Square_(cropped).jpg" },
  "Budapest": { img:"images/cities/budapest.jpg", page:"https://commons.wikimedia.org/wiki/File:View_from_Gell%C3%A9rt_Hill_to_the_Danube%2C_Hungary_-_Budapest_(28493220635).jpg" },
  "Buenos Aires": { img:"images/cities/buenos-aires.jpg", page:"https://commons.wikimedia.org/wiki/File:Avenida_9_de_Julio%2C_Buenos_Aires_(40089810910).jpg" },
  "Busan": { img:"images/cities/busan.jpg", page:"https://commons.wikimedia.org/wiki/File:Gwangan_Bridge1.jpg" },
  "Cairo": { img:"images/cities/cairo.jpg", page:"https://commons.wikimedia.org/wiki/File:Cairo_Opera_House%2C_Al_Hurriyah_Park_and_the_Nile_river_(14797782354).jpg" },
  "Cancún": { img:"images/cities/canc-n.jpg", page:"https://commons.wikimedia.org/wiki/File:Cancun_Strand_Luftbild_(22143397586).jpg" },
  "Cape Town": { img:"images/cities/cape-town.jpg", page:"https://commons.wikimedia.org/wiki/File:Camps_bay_(53460319478)_(cropped).jpg" },
  "Chișinău": { img:"images/cities/chi-in-u.jpg", page:"https://commons.wikimedia.org/wiki/File:Consiliul_Municipal_Chi%C8%99in%C4%83u_(cropped).jpg" },
  "Copenhagen": { img:"images/cities/copenhagen.jpg", page:"https://commons.wikimedia.org/wiki/File:2018_-_Christiansborg_from_the_Marble_Bridge.jpg" },
  "Delhi": { img:"images/cities/delhi.jpg", page:"https://commons.wikimedia.org/wiki/File:Jama_Masjid_2011.jpg" },
  "Denpasar": { img:"images/cities/denpasar.jpg", page:"https://commons.wikimedia.org/wiki/File:Aerial_view_of_Bajra_Sandhi_Monument_Denpasar_Bali_Indonesia.jpg" },
  "Doha": { img:"images/cities/doha.jpg", page:"https://commons.wikimedia.org/wiki/File:The_Pearl_Marina_in_Nov_2013.jpg" },
  "Dubai": { img:"images/cities/dubai.jpg", page:"https://en.wikipedia.org/wiki/File:Burj_Khalifa_2021.jpg" },
  "Dublin": { img:"images/cities/dublin.jpg", page:"https://commons.wikimedia.org/wiki/File:Dublin_-_aerial_-_2025-07-07_01.jpg" },
  "Dubrovnik": { img:"images/cities/dubrovnik.jpg", page:"https://commons.wikimedia.org/wiki/File:The_walls_of_the_fortress_and_View_of_the_old_city._panorama.jpg" },
  "Edinburgh": { img:"images/cities/edinburgh.jpg", page:"https://commons.wikimedia.org/wiki/File:Skyline_of_Edinburgh.jpg" },
  "Florence": { img:"images/cities/florence.jpg", page:"https://commons.wikimedia.org/wiki/File:FirenzeDec092023_01.jpg" },
  "Frankfurt am Main": { img:"images/cities/frankfurt-am-main.jpg", page:"https://en.wikipedia.org/wiki/File:Frankfurt_Main_August_2020_1.jpg" },
  "Fukuoka": { img:"images/cities/fukuoka.jpg", page:"https://commons.wikimedia.org/wiki/File:Fukuoka_Skyline_of_Seaside_Momochi.jpg" },
  "Guangzhou": { img:"images/cities/guangzhou.jpg", page:"https://commons.wikimedia.org/wiki/File:Canton_Tower_20241027.jpg" },
  "Hanoi": { img:"images/cities/hanoi.jpg", page:"https://commons.wikimedia.org/wiki/File:Hanoi_skyline_with_Ba_Vi_Mountain.jpg" },
  "Helsinki": { img:"images/cities/helsinki.jpg", page:"https://commons.wikimedia.org/wiki/File:Suomenlinna_(cropped).jpg" },
  "Heraklion": { img:"images/cities/heraklion.jpg", page:"https://commons.wikimedia.org/wiki/File:Heraklion_old_harbour_in_Crete,_Greece_002.jpg" },
  "Ho Chi Minh City": { img:"images/cities/ho-chi-minh-city.jpg", page:"https://commons.wikimedia.org/wiki/File:Ho_Chi_Minh_City_panorama_2019_(cropped2).jpg" },
  "Hong Kong": { img:"images/cities/hong-kong.jpg", page:"https://commons.wikimedia.org/wiki/File:Hong_Kong_Skyline_viewed_from_Victoria_Peak.jpg" },
  "Honolulu": { img:"images/cities/honolulu.jpg", page:"https://commons.wikimedia.org/wiki/File:2022_Views_from_Diamond_Head_02.jpg" },
  "Istanbul": { img:"images/cities/istanbul.jpg", page:"https://commons.wikimedia.org/wiki/File:Historical_peninsula_and_modern_skyline_of_Istanbul.jpg" },
  "Jerusalem": { img:"images/cities/jerusalem.jpg", page:"https://commons.wikimedia.org/wiki/File:Dome_of_the_Rock_seen_from_the_Mount_of_Olives_(12395649153)_(cropped).jpg" },
  "Johor Bahru": { img:"images/cities/johor-bahru.jpg", page:"https://commons.wikimedia.org/wiki/File:Johor_Bahru_at_night.png" },
  "Kotor": { img:"images/cities/kotor.jpg", page:"https://commons.wikimedia.org/wiki/File:20090719_Crkva_Gospa_od_Zdravlja_Kotor_Bay_Montenegro.jpg" },
  "Kraków": { img:"images/cities/krak-w.jpg", page:"https://commons.wikimedia.org/wiki/File:Krakow_Rynek_Glowny_panorama_2.jpg" },
  "Kuala Lumpur": { img:"images/cities/kuala-lumpur.jpg", page:"https://commons.wikimedia.org/wiki/File:Bukit_Bintang_junction_in_2024_2.jpg" },
  "Kyiv": { img:"images/cities/kyiv.jpg", page:"https://commons.wikimedia.org/wiki/File:%D0%91%D1%83%D0%B4%D0%B8%D0%BD%D0%BE%D0%BA_%D0%B7_%D1%85%D0%B8%D0%BC%D0%B5%D1%80%D0%B0%D0%BC%D0%B8%2C_%D1%81%D0%B5%D1%80%D0%BF%D0%B5%D0%BD%D1%8C_2019.jpg" },
  "Kyoto": { img:"images/cities/kyoto.jpg", page:"https://commons.wikimedia.org/wiki/File:Kiyomizu.jpg" },
  "Las Vegas": { img:"images/cities/las-vegas.jpg", page:"https://commons.wikimedia.org/wiki/File:Las_Vegas_from_above_(40064746644).jpg" },
  "Lima": { img:"images/cities/lima.jpg", page:"https://commons.wikimedia.org/wiki/File:Bas%C3%ADlica_Catedral_Metropolitana_de_Lima_(cropped).jpg" },
  "Lisbon": { img:"images/cities/lisbon.jpg", page:"https://commons.wikimedia.org/wiki/File:Lisboa_-_Portugal_(52597836992).jpg" },
  "Ljubljana": { img:"images/cities/ljubljana.jpg", page:"https://commons.wikimedia.org/wiki/File:Ljubljana_Old_Town%2C_Slovenia_(Old_Camera)_(33286165680).jpg" },
  "London": { img:"images/cities/london.jpg", page:"https://commons.wikimedia.org/wiki/File:London_Skyline_(125508655).jpeg" },
  "Los Angeles": { img:"images/cities/los-angeles.jpg", page:"https://commons.wikimedia.org/wiki/File:Hollywood_Sign_(Zuschnitt).jpg" },
  "Luxembourg City": { img:"images/cities/luxembourg-city.jpg", page:"https://commons.wikimedia.org/wiki/File:Luxembourg_Grand_Ducal_Palace_01.jpg" },
  "Macau": { img:"images/cities/macau.jpg", page:"https://commons.wikimedia.org/wiki/File:%E5%A4%A7%E4%B8%89%E5%B7%B4%E7%89%8C%E5%9D%8A.jpg" },
  "Madrid": { img:"images/cities/madrid.jpg", page:"https://commons.wikimedia.org/wiki/File:Plaza_Mayor_De_Madrid_(215862629)_edited.jpeg" },
  "Marne-la-Vallée": { img:"images/cities/marne-la-vall-e.jpg", page:"https://en.wikipedia.org/wiki/File:Sleeping_Beauty_Castle%2C_Disneyland%2C_Paris.jpg" },
  "Marrakech": { img:"images/cities/marrakech.jpg", page:"https://commons.wikimedia.org/wiki/File:Pavillon_Menarag%C3%A4rten.jpg" },
  "Mecca": { img:"images/cities/mecca.jpg", page:"https://commons.wikimedia.org/wiki/File:Great_Mosque_of_Mecca1.jpg" },
  "Medina": { img:"images/cities/medina.jpg", page:"https://commons.wikimedia.org/wiki/File:Al-Masjid_An-Nabawi_(Bird's_Eye_View).jpg" },
  "Melbourne": { img:"images/cities/melbourne.jpg", page:"https://commons.wikimedia.org/wiki/File:Melbourne_skyline_sor.jpg" },
  "Mexico City": { img:"images/cities/mexico-city.jpg", page:"https://commons.wikimedia.org/wiki/File:Sobrevuelos_CDMX_HJ2A4913_(25514321687)_(cropped).jpg" },
  "Miami": { img:"images/cities/miami.jpg", page:"https://commons.wikimedia.org/wiki/File:Villa_Vizcaya_20110228.jpg" },
  "Milan": { img:"images/cities/milan.jpg", page:"https://commons.wikimedia.org/wiki/File:Milan_-_Scala_-_Facade.jpg" },
  "Minsk": { img:"images/cities/minsk.jpg", page:"https://commons.wikimedia.org/wiki/File:View_of_Minsk_(180819)_09.jpg" },
  "Monaco": { img:"images/cities/monaco.jpg", page:"https://commons.wikimedia.org/wiki/File:Panorama_von_Monaco-La_Turbie.jpg" },
  "Montreal": { img:"images/cities/montreal.jpg", page:"https://commons.wikimedia.org/wiki/File:Montreal%2C_Quebec_skyline.jpg" },
  "Moscow": { img:"images/cities/moscow.jpg", page:"https://commons.wikimedia.org/wiki/File:Saint_Basil's_Cathedral_and_the_Red_Square.jpg" },
  "Munich": { img:"images/cities/munich.jpg", page:"https://commons.wikimedia.org/wiki/File:Stadtbild_M%C3%BCnchen.jpg" },
  "New York": { img:"images/cities/new-york.jpg", page:"https://commons.wikimedia.org/wiki/File:View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_(cropped).jpg" },
  "Nice": { img:"images/cities/nice.jpg", page:"https://commons.wikimedia.org/wiki/File:Promenade_des_Anglais_Nice_IMG_1255.jpg" },
  "Orlando": { img:"images/cities/orlando.jpg", page:"https://commons.wikimedia.org/wiki/File:Orlando%2C_Florida_(cropped).jpg" },
  "Osaka": { img:"images/cities/osaka.jpg", page:"https://commons.wikimedia.org/wiki/File:Osaka_Castle_02bs3200.jpg" },
  "Oslo": { img:"images/cities/oslo.jpg", page:"https://commons.wikimedia.org/wiki/File:Nationaltheatret_evening.jpg" },
  "Palma de Mallorca": { img:"images/cities/palma-de-mallorca.jpg", page:"https://commons.wikimedia.org/wiki/File:Kathedrale_von_Palma.jpg" },
  "Paris": { img:"images/cities/paris.jpg", page:"https://commons.wikimedia.org/wiki/File:La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_(2).jpg" },
  "Pattaya-Chonburi": { img:"images/cities/pattaya-chonburi.jpg", page:"https://commons.wikimedia.org/wiki/File:Pattaya_beach_from_view_point.jpg" },
  "Phuket": { img:"images/cities/phuket.jpg", page:"https://commons.wikimedia.org/wiki/File:Phuket_Aerial.jpg" },
  "Porto": { img:"images/cities/porto.jpg", page:"https://commons.wikimedia.org/wiki/File:Puente_Don_Luis_I%2C_Oporto%2C_Portugal%2C_2012-05-09%2C_DD_13.JPG" },
  "Prague": { img:"images/cities/prague.jpg", page:"https://commons.wikimedia.org/wiki/File:Prague_(6365119737).jpg" },
  "Punta Cana": { img:"images/cities/punta-cana.jpg", page:"https://commons.wikimedia.org/wiki/File:Cap_Cana_Marina_Dominican_Republic.jpg" },
  "Reykjavík": { img:"images/cities/reykjav-k.jpg", page:"https://commons.wikimedia.org/wiki/File:Reykjav%C3%ADk%2C_view_from_Hallgr%C3%ADmskirkja_(2).jpg" },
  "Rhodes": { img:"images/cities/rhodes.jpg", page:"https://commons.wikimedia.org/wiki/File:Medieval_City_of_Rhodes_03.jpg" },
  "Riga": { img:"images/cities/riga.jpg", page:"https://commons.wikimedia.org/wiki/File:Riga_(33844464828).jpg" },
  "Rio de Janeiro": { img:"images/cities/rio-de-janeiro.jpg", page:"https://commons.wikimedia.org/wiki/File:Cidade_Maravilhosa.jpg" },
  "Riyadh": { img:"images/cities/riyadh.jpg", page:"https://commons.wikimedia.org/wiki/File:Riyadh_Skyline.jpg" },
  "Jeddah": { img:"images/cities/jeddah.jpg", page:"https://commons.wikimedia.org/wiki/File:Jeddah_skyline_February_2020.jpg" },
  "Rome": { img:"images/cities/rome.jpg", page:"https://commons.wikimedia.org/wiki/File:Trevi_Fountain%2C_Rome%2C_Italy_2_-_May_2007.jpg" },
  "San Francisco": { img:"images/cities/san-francisco.jpg", page:"https://commons.wikimedia.org/wiki/File:San_Francisco_Downtown_Aerial%2C_August_2025.jpg" },
  "San Marino": { img:"images/cities/san-marino.jpg", page:"https://commons.wikimedia.org/wiki/File:Basilica_del_Santo_Marino%2C_San_Marino%2C_2022-09-20%2C_DD_11.jpg" },
  "Santiago": { img:"images/cities/santiago.jpg", page:"https://commons.wikimedia.org/wiki/File:Palacio_de_La_Moneda_-_miguelreflex.jpg" },
  "São Paulo": { img:"images/cities/s-o-paulo.jpg", page:"https://commons.wikimedia.org/wiki/File:Marginal_Pinheiros_e_Jockey_Club.jpg" },
  "Sapporo": { img:"images/cities/sapporo.jpg", page:"https://commons.wikimedia.org/wiki/File:SapporoCity_Skylines2020.jpg" },
  "Sarajevo": { img:"images/cities/sarajevo.jpg", page:"https://commons.wikimedia.org/wiki/File:Sarajevo_City_Panorama.JPG" },
  "Seoul": { img:"images/cities/seoul.jpg", page:"https://en.wikipedia.org/wiki/File:%EC%A4%91%ED%99%94%EC%A0%84%EC%9D%98_%EB%82%AE.jpg" },
  "Seville": { img:"images/cities/seville.jpg", page:"https://commons.wikimedia.org/wiki/File:Sevilla_Cathedral_-_Southeast.jpg" },
  "Shanghai": { img:"images/cities/shanghai.jpg", page:"https://commons.wikimedia.org/wiki/File:Huangpu_Park_20124-Shanghai_(32208802494).jpg" },
  "Sharjah": { img:"images/cities/sharjah.jpg", page:"https://commons.wikimedia.org/wiki/File:Al_Qasba.jpg" },
  "Shenzhen": { img:"images/cities/shenzhen.jpg", page:"https://commons.wikimedia.org/wiki/File:Commercial_area_of_futian_to_east2020.jpg" },
  "Singapore": { img:"images/cities/singapore.jpg", page:"https://commons.wikimedia.org/wiki/File:Singapore_Skyline_2019-10.jpg" },
  "Skopje": { img:"images/cities/skopje.jpg", page:"https://commons.wikimedia.org/wiki/File:Skopje_view_from_Kale_3.jpg" },
  "Sofia": { img:"images/cities/sofia.jpg", page:"https://commons.wikimedia.org/wiki/File:Russian_church_(37591925970).jpg" },
  "Stockholm": { img:"images/cities/stockholm.jpg", page:"https://commons.wikimedia.org/wiki/File:Royal_Dramatic_Theatre_Stockholm.jpg" },
  "Sydney": { img:"images/cities/sydney.jpg", page:"https://commons.wikimedia.org/wiki/File:Sydney_Opera_House_and_Harbour_Bridge_Dusk_(2)_2019-06-21.jpg" },
  "Taipei": { img:"images/cities/taipei.jpg", page:"https://commons.wikimedia.org/wiki/File:Taipei_Skyline_2022.06.29.jpg" },
  "Tallinn": { img:"images/cities/tallinn.jpg", page:"https://commons.wikimedia.org/wiki/File:Raekoja_plats_at_night.jpg" },
  "Tbilisi": { img:"images/cities/tbilisi.jpg", page:"https://commons.wikimedia.org/wiki/File:View_of_Tbilisi_from_Tabori_Church_2023-10-08-2.jpg" },
  "Tel Aviv": { img:"images/cities/tel-aviv.jpg", page:"https://commons.wikimedia.org/wiki/File:Sarona_CBD_01_(cropped).jpg" },
  "Thessaloniki": { img:"images/cities/thessaloniki.jpg", page:"https://commons.wikimedia.org/wiki/File:Thessaloniki_Heptapyrgion_northeastern_wall_from_the_inner_yard.jpg" },
  "Tirana": { img:"images/cities/tirana.jpg", page:"https://commons.wikimedia.org/wiki/File:Skanderbeg_square_tirana_2016.jpg" },
  "Tokyo": { img:"images/cities/tokyo.jpg", page:"https://en.wikipedia.org/wiki/File:Skyscrapers_of_Shinjuku_2009_January.jpg" },
  "Toronto": { img:"images/cities/toronto.jpg", page:"https://commons.wikimedia.org/wiki/File:Toronto_Skyline_from_Olympic_Island%2C_June_20_2026_(5-3_cropped).jpg" },
  "Vaduz": { img:"images/cities/vaduz.jpg", page:"https://commons.wikimedia.org/wiki/File:View_of_Vaduz.jpg" },
  "Valencia": { img:"images/cities/valencia.jpg", page:"https://commons.wikimedia.org/wiki/File:Malvarrosa_Beach%2C_Valencia%2C_Spain_(29812271043).jpg" },
  "Valletta": { img:"images/cities/valletta.jpg", page:"https://commons.wikimedia.org/wiki/File:St_Sebastian_Curtain_(cropped).jpg" },
  "Vancouver": { img:"images/cities/vancouver.jpg", page:"https://commons.wikimedia.org/wiki/File:Skyline_of_Vancouver%2C_Canada.jpg" },
  "Venice": { img:"images/cities/venice.jpg", page:"https://commons.wikimedia.org/wiki/File:Venezia_aerial_view.jpg" },
  "Verona": { img:"images/cities/verona.jpg", page:"https://commons.wikimedia.org/wiki/File:Tramonto_a_Verona.jpg" },
  "Vienna": { img:"images/cities/vienna.jpg", page:"https://commons.wikimedia.org/wiki/File:Schoenbrunn_philharmoniker_2012.jpg" },
  "Vilnius": { img:"images/cities/vilnius.jpg", page:"https://en.wikipedia.org/wiki/File:The_White_Bridge_and_%C5%A0nipi%C5%A1k%C4%97s_district_in_Vilnius_in_2023_by_Augustas_Did%C5%BEgalvis.jpg" },
  "Warsaw": { img:"images/cities/warsaw.jpg", page:"https://commons.wikimedia.org/wiki/File:Aleja_Niepdleglosci_Warsaw_2022_aerial_(cropped).jpg" },
  "Washington, D.C.": { img:"images/cities/washington-d-c.jpg", page:"https://commons.wikimedia.org/wiki/File:12-07-13-washington-by-RalfR-08.jpg" },
  "Zhuhai": { img:"images/cities/zhuhai.jpg", page:"https://commons.wikimedia.org/wiki/File:%E4%BB%8E%E5%87%A4%E5%87%B0%E5%B1%B1%E8%BF%9C%E7%9C%BA%E7%8F%A0%E6%B5%B7%E4%B8%BB%E5%9F%8E%E5%8C%BA.jpg" },
  "Zurich": { img:"images/cities/zurich.jpg", page:"https://commons.wikimedia.org/wiki/File:Altstadt_Z%C3%BCrich_2015.jpg" },
  "Abidjan": { img:"images/cities/abidjan.jpg", page:"https://en.wikipedia.org/wiki/File:Visite_du_mus%C3%A9e_de_civilisation_de_C%C3%B4te_d'Ivoire_08.jpg" },
  "Accra": { img:"images/cities/accra.jpg", page:"https://en.wikipedia.org/wiki/File:Acca.jpg" },
  "Addis Ababa": { img:"images/cities/addis-ababa.jpg", page:"https://en.wikipedia.org/wiki/File:Addis_in_night.jpg" },
  "Algiers": { img:"images/cities/algiers.jpg", page:"https://en.wikipedia.org/wiki/File:Botanical_Garden_Hamma.jpg" },
  "Almaty": { img:"images/cities/almaty.jpg", page:"https://en.wikipedia.org/wiki/File:Almaty_K%C3%B6k_T%C3%B6be.jpg" },
  "Amman": { img:"images/cities/amman.jpg", page:"https://en.wikipedia.org/wiki/File:New_Abdali_2024.png" },
  "Antananarivo": { img:"images/cities/antananarivo.jpg", page:"https://en.wikipedia.org/wiki/File:Lake_Anosy%2C_Central_Antananarivo%2C_Capital_of_Madagascar%2C_Photo_by_Sascha_Grabow.jpg" },
  "Apia": { img:"images/cities/apia.jpg", page:"https://en.wikipedia.org/wiki/File:WS-apia-regierg.jpg" },
  "Ashgabat": { img:"images/cities/ashgabat.jpg", page:"https://en.wikipedia.org/wiki/File:View_of_Ashgabat_(42376779291).jpg" },
  "Asmara": { img:"images/cities/asmara.jpg", page:"https://commons.wikimedia.org/wiki/File:Fiat_Tagliero_Building.jpg" },
  "Asunción": { img:"images/cities/asunci-n.jpg", page:"https://en.wikipedia.org/wiki/File:Palacio_de_Gobierno2.jpg" },
  "Auckland": { img:"images/cities/auckland.jpg", page:"https://en.wikipedia.org/wiki/File:Auckland_skyline_-_May_2024_(2).jpg" },
  "Baghdad": { img:"images/cities/baghdad.jpg", page:"https://en.wikipedia.org/wiki/File:5628442718_b10fc2c47f_o.jpg" },
  "Baku": { img:"images/cities/baku.jpg", page:"https://commons.wikimedia.org/wiki/File:Baku_Skyline_qiz_qalasi.jpg" },
  "Bamako": { img:"images/cities/bamako.jpg", page:"https://en.wikipedia.org/wiki/File:Place_de_la_libert%C3%A9_-_Bamako.jpg" },
  "Bandar Seri Begawan": { img:"images/cities/bandar-seri-begawan.jpg", page:"https://en.wikipedia.org/wiki/File:Brunei_Fireworks_%26_Drone_Light_Show_2024_12.jpg" },
  "Bangui": { img:"images/cities/bangui.jpg", page:"https://commons.wikimedia.org/wiki/File:Bangui_City_Centre.jpg" },
  "Banjul": { img:"images/cities/banjul.jpg", page:"https://en.wikipedia.org/wiki/File:Gambia%2C_Banjul%2C_Arch_22.jpg" },
  "Basseterre": { img:"images/cities/basseterre.jpg", page:"https://en.wikipedia.org/wiki/File:St._Kitts%2C_Karibik_-_Marina_in_Basseterre_-_panoramio.jpg" },
  "Beirut": { img:"images/cities/beirut.jpg", page:"https://en.wikipedia.org/wiki/File:Beyrouth_vue_a%C3%A9rienne.jpg" },
  "Belize City": { img:"images/cities/belize-city.jpg", page:"https://commons.wikimedia.org/wiki/File:Belize_City_harbour,_Belize.jpg" },
  "Bishkek": { img:"images/cities/bishkek.jpg", page:"https://en.wikipedia.org/wiki/File:Bishkek_City's_business_center.jpg" },
  "Bissau": { img:"images/cities/bissau.jpg", page:"https://en.wikipedia.org/wiki/File:Bissau-Stroossenzeen--w.jpg" },
  "Bogotá": { img:"images/cities/bogot.jpg", page:"https://en.wikipedia.org/wiki/File:Bogota%2C_Colombia_(36668708290).jpg" },
  "Brazzaville": { img:"images/cities/brazzaville.jpg", page:"https://en.wikipedia.org/wiki/File:Les_lieux_de_Brazzaville_03.jpg" },
  "Bridgetown": { img:"images/cities/bridgetown.jpg", page:"https://en.wikipedia.org/wiki/File:Bridgetown2.jpg" },
  "Bujumbura": { img:"images/cities/bujumbura.jpg", page:"https://en.wikipedia.org/wiki/File:BujumburaFromCathedral.jpg" },
  "Caracas": { img:"images/cities/caracas.jpg", page:"https://en.wikipedia.org/wiki/File:Caracas_desde_el_%C3%A1vila.jpg" },
  "Castries": { img:"images/cities/castries.jpg", page:"https://en.wikipedia.org/wiki/File:View_of_Castries_Saint_Lucia_Day248bdriveb.jpg" },
  "Colombo": { img:"images/cities/colombo.jpg", page:"https://en.wikipedia.org/wiki/File:Colombo_city_skyline_at_night.png" },
  "Conakry": { img:"images/cities/conakry.jpg", page:"https://en.wikipedia.org/wiki/File:Ville_de_Conaky.jpg" },
  "Cotonou": { img:"images/cities/cotonou.jpg", page:"https://en.wikipedia.org/wiki/File:Vue_panoramique_quartier_cadj%C3%A9houn-Cotonou_au_B%C3%A9nin.jpg" },
  "Dakar": { img:"images/cities/dakar.jpg", page:"https://en.wikipedia.org/wiki/File:Dakar-Ind%C3%A9pendance.jpg" },
  "Damascus": { img:"images/cities/damascus.jpg", page:"https://en.wikipedia.org/wiki/File:Damascus%2C_Syria%2C_Panoramic_view_of_Damascus.jpg" },
  "Dhaka": { img:"images/cities/dhaka.jpg", page:"https://en.wikipedia.org/wiki/File:Drone_view_from_Kamal_Atat%C3%BCrk_Avenue.jpg" },
  "Dili": { img:"images/cities/dili.jpg", page:"https://en.wikipedia.org/wiki/File:Government_Palace%2C_Dili%2C_2023_(02).jpg" },
  "Djibouti City": { img:"images/cities/djibouti-city.jpg", page:"https://commons.wikimedia.org/wiki/File:Place_Menelik_in_Djibouti_city_(25058480721).jpg" },
  "Douala": { img:"images/cities/douala.jpg", page:"https://en.wikipedia.org/wiki/File:Quarter_Bali_%C3%A0_Douala_Cameroun.jpg" },
  "Dushanbe": { img:"images/cities/dushanbe.jpg", page:"https://en.wikipedia.org/wiki/File:Panorama_with_buildings%2C_Dushanbe.jpg" },
  "Freetown": { img:"images/cities/freetown.jpg", page:"https://en.wikipedia.org/wiki/File:Freetown-aerialview.jpg" },
  "Funafuti": { img:"images/cities/funafuti.jpg", page:"https://en.wikipedia.org/wiki/File:Funafuti_airport_-_Fiji_Airways.jpg" },
  "Gaborone": { img:"images/cities/gaborone.jpg", page:"https://en.wikipedia.org/wiki/File:View_from_I-Tower_SE_20200712.jpg" },
  "Georgetown": { img:"images/cities/georgetown.jpg", page:"https://en.wikipedia.org/wiki/File:Guyana_Parliament_Building.jpg" },
  "Guatemala City": { img:"images/cities/guatemala-city.jpg", page:"https://en.wikipedia.org/wiki/File:Ciudad_de_Guatemala%2C_CA.jpg" },
  "Havana": { img:"images/cities/havana.jpg", page:"https://en.wikipedia.org/wiki/File:DJI_0197_crp_wiki.jpg" },
  "Honiara": { img:"images/cities/honiara.jpg", page:"https://en.wikipedia.org/wiki/File:Honiara_View.jpg" },
  "Juba": { img:"images/cities/juba.jpg", page:"https://en.wikipedia.org/wiki/File:John_Garang_Mausoleum_Square_in_Juba.JPG" },
  "Kabul": { img:"images/cities/kabul.jpg", page:"https://en.wikipedia.org/wiki/File:Kabul%2C_Afghanistan_view.jpg" },
  "Kampala": { img:"images/cities/kampala.jpg", page:"https://en.wikipedia.org/wiki/File:Urban_Rising%2C_KAMPALA%2C_Uganda.jpg" },
  "Karachi": { img:"images/cities/karachi.jpg", page:"https://en.wikipedia.org/wiki/File:Clifton_Karachi_View.jpg" },
  "Kathmandu": { img:"images/cities/kathmandu.jpg", page:"https://en.wikipedia.org/wiki/File:Kathmandu-Durbar_Square-06-Mahavishnu-Kuh-Vishnu-Pratapamalla-Jagannath-2007-gje.jpg" },
  "Khartoum": { img:"images/cities/khartoum.jpg", page:"https://en.wikipedia.org/wiki/File:%C2%A9Nile-Project_-Sari_Omer_0025.jpg" },
  "Kigali": { img:"images/cities/kigali.jpg", page:"https://en.wikipedia.org/wiki/File:High_Angle_View_Of_Kigali_City_Street_on_November_29%2C_2018._Emmanuel_Kwizera.jpg" },
  "Kingstown": { img:"images/cities/kingstown.jpg", page:"https://en.wikipedia.org/wiki/File:Kingstown.jpg" },
  "Kinshasa": { img:"images/cities/kinshasa.jpg", page:"https://en.wikipedia.org/wiki/File:La_Gombe%2C_Kinshasa%2C_RDC_(cropped).jpg" },
  "Koror": { img:"images/cities/koror.jpg", page:"https://en.wikipedia.org/wiki/File:Main_St%2C_Koror%2C_Palau_-_panoramio_(1).jpg" },
  "Kuwait City": { img:"images/cities/kuwait-city.jpg", page:"https://en.wikipedia.org/wiki/File:Kuwait_City_Skyline_1.jpg" },
  "La Paz": { img:"images/cities/la-paz.jpg", page:"https://en.wikipedia.org/wiki/File:Vista_del_centro_de_La_Paz.jpg" },
  "Lagos": { img:"images/cities/lagos.jpg", page:"https://en.wikipedia.org/wiki/File:Tafa_Balewa_Square_(Onikan)_in_Lagos._Nigeria.jpg" },
  "Libreville": { img:"images/cities/libreville.jpg", page:"https://en.wikipedia.org/wiki/File:Libreville_frond_de_mer.jpg" },
  "Lilongwe": { img:"images/cities/lilongwe.jpg", page:"https://en.wikipedia.org/wiki/File:K.a.r-.clocktower-in-lilongwe.jpg" },
  "Lomé": { img:"images/cities/lom.jpg", page:"https://en.wikipedia.org/wiki/File:C%E2%80%99est_Lom%C3%A9.jpg" },
  "Luanda": { img:"images/cities/luanda.jpg", page:"https://en.wikipedia.org/wiki/File:Luanda_2025_focused_(cropped).jpg" },
  "Lusaka": { img:"images/cities/lusaka.jpg", page:"https://en.wikipedia.org/wiki/File:Downtown_Lusaka.JPG" },
  "Majuro": { img:"images/cities/majuro.jpg", page:"https://en.wikipedia.org/wiki/File:Eneko_Islet_02.JPG" },
  "Malabo": { img:"images/cities/malabo.jpg", page:"https://en.wikipedia.org/wiki/File:Hotel_de_Federaciones_02.jpg" },
  "Malé": { img:"images/cities/mal.jpg", page:"https://en.wikipedia.org/wiki/File:Mal%C3%A9.jpg" },
  "Managua": { img:"images/cities/managua.jpg", page:"https://en.wikipedia.org/wiki/File:%D0%9A%D0%B0%D1%84%D0%B5%D0%B4%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9_%D1%81%D0%BE%D0%B1%D0%BE%D1%80_%D0%B2_%D0%9C%D0%B0%D0%BD%D0%B0%D0%B3%D1%83%D0%B0_(cropped).jpg" },
  "Manama": { img:"images/cities/manama.jpg", page:"https://en.wikipedia.org/wiki/File:Manama%2C_Bahrain_Decembre_2014.jpg" },
  "Manila": { img:"images/cities/manila.jpg", page:"https://en.wikipedia.org/wiki/File:Cityscape_of_Manila%2C_2025_(01).jpg" },
  "Maputo": { img:"images/cities/maputo.jpg", page:"https://en.wikipedia.org/wiki/File:Maputo_seen_from_southeast_-_October_2006_(cropped).jpg" },
  "Maseru": { img:"images/cities/maseru.jpg", page:"https://en.wikipedia.org/wiki/File:Maseru_City_CBD.jpg" },
  "Mbabane": { img:"images/cities/mbabane.jpg", page:"https://en.wikipedia.org/wiki/File:Mbabane_(6035476964).jpg" },
  "Mogadishu": { img:"images/cities/mogadishu.jpg", page:"https://en.wikipedia.org/wiki/File:Lido_beach_from_the_sea_in_Mogadishu.jpg" },
  "Monrovia": { img:"images/cities/monrovia.jpg", page:"https://en.wikipedia.org/wiki/File:Liberia%2C_Africa_-_panoramio_(256).jpg" },
  "Montego Bay": { img:"images/cities/montego-bay.jpg", page:"https://en.wikipedia.org/wiki/File:Montego_Bay_Photo_Don_Ramey_Logan.jpg" },
  "Montevideo": { img:"images/cities/montevideo.jpg", page:"https://en.wikipedia.org/wiki/File:PALACIO_LEGISLATIVO_01.JPG" },
  "Moroni": { img:"images/cities/moroni.jpg", page:"https://en.wikipedia.org/wiki/File:Moroni-Harbour.jpg" },
  "Muscat": { img:"images/cities/muscat.jpg", page:"https://en.wikipedia.org/wiki/File:Al_Alam_Palace.jpg" },
  "N'Djamena": { img:"images/cities/n-djamena.jpg", page:"https://en.wikipedia.org/wiki/File:Building_of_National_Assembly_DJAMENA.jpg" },
  "Nadi": { img:"images/cities/nadi.jpg", page:"https://en.wikipedia.org/wiki/File:Nadi.jpg" },
  "Nairobi": { img:"images/cities/nairobi.jpg", page:"https://en.wikipedia.org/wiki/File:Nairobi_skyline_from_Gem_Hotel.jpg" },
  "Nassau": { img:"images/cities/nassau.jpg", page:"https://en.wikipedia.org/wiki/File:Nassau%2C_Bahamas_aerial_view_(cropped).jpg" },
  "Niamey": { img:"images/cities/niamey.jpg", page:"https://en.wikipedia.org/wiki/File:Niamey_from_grand_mosque_theatre_2006.jpg" },
  "Nicosia": { img:"images/cities/nicosia.jpg", page:"https://en.wikipedia.org/wiki/File:Nicosia's_skyline_2024.jpg" },
  "Nouakchott": { img:"images/cities/nouakchott.jpg", page:"https://en.wikipedia.org/wiki/File:Nouakchott.jpg" },
  "Nuku'alofa": { img:"images/cities/nuku-alofa.jpg", page:"https://en.wikipedia.org/wiki/File:Royal_Palace%2C_Nuku'alofa%2C_Nov_18.jpg" },
  "Ouagadougou": { img:"images/cities/ouagadougou.jpg", page:"https://en.wikipedia.org/wiki/File:Ouagadougou_Skyline.jpg" },
  "Panama City": { img:"images/cities/panama-city.jpg", page:"https://en.wikipedia.org/wiki/File:Panama_Papers_(148830809).jpeg" },
  "Paramaribo": { img:"images/cities/paramaribo.jpg", page:"https://commons.wikimedia.org/wiki/File:Paramaribo_district_07.jpg" },
  "Port Louis": { img:"images/cities/port-louis.jpg", page:"https://en.wikipedia.org/wiki/File:Port_Louis_Skyline.JPG" },
  "Port Moresby": { img:"images/cities/port-moresby.jpg", page:"https://en.wikipedia.org/wiki/File:Port_Moresby_Town2_Mschlauch.jpg" },
  "Port Vila": { img:"images/cities/port-vila.jpg", page:"https://en.wikipedia.org/wiki/File:Port_Vila_aerial.jpg" },
  "Port of Spain": { img:"images/cities/port-of-spain.jpg", page:"https://en.wikipedia.org/wiki/File:POS_at_night_Skyline.jpg" },
  "Port-au-Prince": { img:"images/cities/port-au-prince.jpg", page:"https://en.wikipedia.org/wiki/File:Ouest_Department%2C_Haiti_-_panoramio_(5).jpg" },
  "Praia": { img:"images/cities/praia.jpg", page:"https://en.wikipedia.org/wiki/File:Pal%C3%A1cio_da_Cultura%2C_Praia%2C_Cape_Verde.jpg" },
  "Pyongyang": { img:"images/cities/pyongyang.jpg", page:"https://en.wikipedia.org/wiki/File:The_Arch_of_Triumph_(11360607534).jpg" },
  "Quito": { img:"images/cities/quito.jpg", page:"https://en.wikipedia.org/wiki/File:FACHADA_ASAMBLEA_NACIONAL._QUITO%2C_20_DE_FEBRERO_2020._01.jpg" },
  "Roseau": { img:"images/cities/roseau.jpg", page:"https://en.wikipedia.org/wiki/File:Roseau_Dominica.jpg" },
  "San José": { img:"images/cities/san-jos.jpg", page:"https://commons.wikimedia.org/wiki/File:Cityscape_of_San_Jos%C3%A9,_Costa_Rica_(253552473).jpg" },
  "San Salvador": { img:"images/cities/san-salvador.jpg", page:"https://en.wikipedia.org/wiki/File:Monumento_al_Salvador_del_Mundo_1.jpg" },
  "Sana'a": { img:"images/cities/sana-a.jpg", page:"https://en.wikipedia.org/wiki/File:Sana'a_(2286825748).jpg" },
  "Siem Reap": { img:"images/cities/siem-reap.jpg", page:"https://en.wikipedia.org/wiki/File:Front_porch_of_Wat_Damnak.jpg" },
  "St. George's": { img:"images/cities/st-george-s.jpg", page:"https://en.wikipedia.org/wiki/File:St_Georges_Grenada_Fort_-_panoramio.jpg" },
  "St. John's": { img:"images/cities/st-john-s.jpg", page:"https://en.wikipedia.org/wiki/File:St_Johns_Antigua_2012.jpg" },
  "São Tomé": { img:"images/cities/s-o-tom.jpg", page:"https://en.wikipedia.org/wiki/File:2012SaoTome-8_(8042889363).jpg" },
  "Tarawa": { img:"images/cities/tarawa.jpg", page:"https://en.wikipedia.org/wiki/File:South_Tarawa_from_the_air.jpg" },
  "Tashkent": { img:"images/cities/tashkent.jpg", page:"https://en.wikipedia.org/wiki/File:Nest_One_Tashkent.jpg" },
  "Tegucigalpa": { img:"images/cities/tegucigalpa.jpg", page:"https://en.wikipedia.org/wiki/File:Tegucigalpa_downtown_panoramic_2026.jpg" },
  "Tehran": { img:"images/cities/tehran.jpg", page:"https://en.wikipedia.org/wiki/File:North_of_Tehran_Skyline_view.jpg" },
  "Thimphu": { img:"images/cities/thimphu.jpg", page:"https://en.wikipedia.org/wiki/File:Tashich%C3%B6dzong_Thimphu-2008-01-23.jpg" },
  "Tripoli": { img:"images/cities/tripoli.jpg", page:"https://en.wikipedia.org/wiki/File:Tripoli_at_night.jpg" },
  "Tunis": { img:"images/cities/tunis.jpg", page:"https://en.wikipedia.org/wiki/File:Minaret_et_patio_de_la_mosqu%C3%A9e_Zitouna_au_centre_de_la_M%C3%A9dina_de_Tunis.jpg" },
  "Ulaanbaatar": { img:"images/cities/ulaanbaatar.jpg", page:"https://en.wikipedia.org/wiki/File:UB_downtown.jpg" },
  "Victoria": { img:"images/cities/victoria.jpg", page:"https://en.wikipedia.org/wiki/File:Victoria_clock_tower.jpg" },
  "Victoria Falls": { img:"images/cities/victoria-falls.jpg", page:"https://en.wikipedia.org/wiki/File:Cataratas_Victoria%2C_Zambia-Zimbabue%2C_2018-07-27%2C_DD_04.jpg" },
  "Vientiane": { img:"images/cities/vientiane.jpg", page:"https://en.wikipedia.org/wiki/File:Vientiane_-_Patuxai_-_0003.jpg" },
  "Weno": { img:"images/cities/weno.jpg", page:"https://en.wikipedia.org/wiki/File:Weno_Chuuk_Mountain.jpg" },
  "Windhoek": { img:"images/cities/windhoek.jpg", page:"https://en.wikipedia.org/wiki/File:Christ_Church_in_Windhoek%2C_Namibia.jpg" },
  "Yangon": { img:"images/cities/yangon.jpg", page:"https://en.wikipedia.org/wiki/File:ShwedagonPagoda.jpg" },
  "Yaren": { img:"images/cities/yaren.jpg", page:"https://en.wikipedia.org/wiki/File:Parliament_(15403802091).jpg" },
  "Yerevan": { img:"images/cities/yerevan.jpg", page:"https://en.wikipedia.org/wiki/File:Mount_Ararat_and_the_Yerevan_skyline_(June_2018).jpg" },
  "Zanzibar City": { img:"images/cities/zanzibar-city.jpg", page:"https://en.wikipedia.org/wiki/File:Malawi_Rd%2C_Zanzibar_Town%2C_Tanzania_-_panoramio.jpg" },
};
